from socket import *
import re
LOGIN_FAIL=0
LOGIN_SUCCESS=1
REGISTER_FAIL=2
REGISTER_SUCCESS=3
MESSAGE=4
LOGIN=5
REGISTER=6
ONLINE=7
OFFLINE=8
LOGOUT=9
FRIENDS=10
ADD_FRIEND=11
USER_OFFLINE=12
ADD_FAIL=13
ADD_SUCCESS=14
ADD_WAIT=15
ADDR = ('localhost', 21567)
ADDR_LOGIN = ('localhost', 21568)

s = socket(AF_INET, SOCK_DGRAM)

register_re = re.compile(r"[\w]{6,}")
